//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_EmpAttendance
    {
        public int ID { get; set; }
        public Nullable<int> EMP_CODE { get; set; }
        public Nullable<int> Attendance { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> In_Time { get; set; }
        public Nullable<System.TimeSpan> Out_Time { get; set; }
        public string Permission { get; set; }
        public string IsLate { get; set; }
        public string Half { get; set; }
        public string Notes { get; set; }
        public string App_User { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
    
        public virtual tb_Employee tb_Employee { get; set; }
    }
}
