//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Employement
    {
        public int ID { get; set; }
        public Nullable<int> EMP_CODE { get; set; }
        public string Branch { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string ReferredBy { get; set; }
        public string Department { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Designation { get; set; }
        public byte[] Resume { get; set; }
        public byte[] OfferLetter { get; set; }
        public string Available { get; set; }
        public Nullable<System.TimeSpan> In_Time { get; set; }
        public Nullable<System.TimeSpan> Out_Time { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
    
        public virtual tb_Employee tb_Employee { get; set; }
    }
}
