//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CITSWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Employee()
        {
            this.tb_EmpAdvance = new HashSet<tb_EmpAdvance>();
            this.tb_EmpAppraisal = new HashSet<tb_EmpAppraisal>();
            this.tb_EmpAttendance = new HashSet<tb_EmpAttendance>();
            this.tb_Employement = new HashSet<tb_Employement>();
            this.tb_EmpPromotion = new HashSet<tb_EmpPromotion>();
            this.tb_EmpSalary = new HashSet<tb_EmpSalary>();
        }
    
        public int ID { get; set; }
        public int EMP_CODE { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string District { get; set; }
        public Nullable<int> Pin { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string ContactNo { get; set; }
        public string EMail { get; set; }
        public string Qualification { get; set; }
        public string BloodGroup { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_EmpAdvance> tb_EmpAdvance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_EmpAppraisal> tb_EmpAppraisal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_EmpAttendance> tb_EmpAttendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Employement> tb_Employement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_EmpPromotion> tb_EmpPromotion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_EmpSalary> tb_EmpSalary { get; set; }
    }
}
